config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
	belongs_to :user
	has_attached_file :image, styles: { thumb: ["100x200#", :jpg],
											                original: ['400x300>', :jpg],
											                medium: ['200x300#', :jpg] },
                convert_options: { thumb: "-quality 75 -strip",
                                   original: "-quality 85 -strip" },
        				default_url: "/images/:style/missing_todo.png"

	validates_attachment_content_type :image,
						      :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	def new
		@todo = Todo.new
	end

	def create
		@todo = current_user.todos.build(todo_params)

		respond_to do |f| 
			if @todo.save
				f.html {redirect_to todos_path}
				f.js {redirect_to todos_path}
			else
				f.html {render :new}
				f.js {render :new}
			end
		end

	end

	def index
		@incomplete_todos = Todo.where(completed: false)
		@complete_todos = Todo.where(completed: true)
		@todo = Todo.new
	end

	def destroy
		@todo = Todo.find(params[:id])
		@todo.destroy
		flash[:danger] = "Your task has been deleted"
		respond_to do |f|
			f.html {redirect_to todos_path}
			f.js
		end
	end

	def update
		@todo = Todo.find(params[:id])
		@todo.update_attributes!(todo_params)

		respond_to do |f|
			f.html {redirect_to todos_path}
			f.js
		end
	end

	
	private
		def todo_params
			params.require(:todo).permit(:title, :body, :image, :user_id, :completed)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-custom
	.container
		.navbar-header
			%button.navbar-toggle.collapsed{"data-target" => "bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
				%span.sr-only Toggle Navigation
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			= link_to "Todo App", root_path, class: "navbar-brand", id: "logo"
		#bs-example-navbar-collapse-1.collapse.navbar-collapse
			%ul.nav.navbar-nav
				%li 
					= link_to "To Do list", todos_path, method: :get
			.pull-right.signing
				- if user_signed_in?
					= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn logout"
				- else
					= link_to "Sign in", user_session_path, class: "btn btn-default sign_in"
					= link_to "Sign up", new_user_registration_path, class: "btn btn-primary sign_up"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Todoapp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .wrapper
      = yield

app/views/todos/_form.html.haml
- if @todo.errors.any?
  %h3 The following errors occured
  %ul
    - @todo.errors.full_messages.each do |msg|
      %li
        = msg
.well
  %h2{:align => "center"} Create your Todo
  = form_for(@todo, remote: true, :html => {:multipart => true, class: "form-horizontal", role: "form"}) do |f|
    .form-group
      .control-label.col-sm-2
        = f.hidden_field :user_id, value: @todo
    .form-group
      .control-label.col-sm-2
        = f.label :title
      .col-sm-8
        = f.text_field :title, class: "form-control", placeholder: "Title of your todo", autofocus: true
    .form-group
      .control-label.col-sm-2
        = f.label :body
      .col-sm-8
        = f.text_field :body, class: "form-control", placeholder: "What do you need to do"
    .form-group
      .control-label.col-sm-2
        = f.label :image
      .col-sm-8
        = f.file_field :image      
    .form-group
      .col-sm-offset-2.col-sm-10
        = f.button class: "btn btn-primary btn-sm", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Signing in..."}

app/views/todos/_todo.html.haml
- obj.each do |td|
  = form_for td, remote: true do |f|
    = f.check_box :completed
    = f.submit "Update"
    = f.label :completed, td.title
    %span.delete 
      = link_to td, method: :delete, data: {confirm: "Are you sure?"}, remote: true do 
        = fa_icon "trash 2x fw"

app/views/todos/create.js.erb
$("#incomplete_todos").append('<%= j render(@todo) %>');
$(document).ready(function (){
	$('#incomplete_todos').submitOnCheck();	
});

app/views/todos/destroy.js.erb
$("#edit_todo_<%= @todo.id %>").remove();

app/views/todos/index.html.haml
= render "layouts/header"
/ .container
/ 	.rows
/ 		.col-sm-6
/ 			.well
/ 				- @todos.each do |td|
/ 					.td-list.clearfix
/ 						.td-title
/ 							%b= td.title
/ 						.td-check.pull-right
/ 							= check_box("Todo", td.id , {checked: true})
/ 						.td-body
/ 							Author:
/ 							%em= td.body
/ 						.td-image
/ 							= image_tag td.image.url
/ 						.td-btn.pull-right
/ 							= link_to todo_path(td.id), method: :delete do
/ 								= fa_icon "trash 2x"

.row
	.col-md-4
		= render 'form'
	.col-md-4
		%h2 Incomplete Todos
		.todos#incomplete_todos
			= render "todo", obj: @incomplete_todos
	.col-md-4
		%h2 Comlpete Todos
		.todos#complete_todos
			= render "todo", obj: @complete_todos

app/views/todos/new.html.haml
= render "layouts/header"
%h2{align: "center"} New task
= render "form"

app/views/todos/new.js.erb
$('#new_link').hide().before('<%= j render("form") %>');

app/views/todos/update.js.erb
<% if @todo.completed? %>
	$('#edit_todo_<%= @todo.id %>').appendTo('#complete_todos');
<% else %>
	$('#edit_todo_<%= @todo.id %>').appendTo('#incomplete_todos');
<% end %>

app/views/welcome/_main-page.html.haml
.container
	.theme-showcase
		.todo-page 
			%h1 Welcome to the TODO  page
			= link_to "Create your todo list", new_todo_path, class: "todo-list"

app/views/welcome/index.html.haml
.todo-wrapper
        = render "layouts/header"
        = render "welcome/main-page"